/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import controller.HotelReservationSystemController;
import view.sub.ReservationListPanel;
import view.sub.RoomListPanel;
import view.sub.SubFrame;

/**
 *
 * @author Rafael
 */
public class ViewPanel extends JPanel implements ActionListener{
    HotelReservationSystemController controller;
    JButton viewReservationButton, refreshButton, viewRoomButton;

    /**
     * Creates new form ViewHotelPanel
     */
    public ViewPanel(HotelReservationSystemController controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hotelListScrollPane = new javax.swing.JScrollPane();
        hotelListTable = new javax.swing.JTable();
        viewReservationButton = new JButton();
        refreshButton = new JButton();
        viewRoomButton = new JButton();

        setPreferredSize(new java.awt.Dimension(570, 480));
        setLayout(null);

        // Create Table Model
        DefaultTableModel tableModel = new DefaultTableModel(0, 4);
        String tableHeader[] = {"Hotel Name", "Base Rate", "No. of Rooms", "No. of Reservations"};
        tableModel.setColumnIdentifiers(tableHeader);
        
        hotelListTable.setModel(tableModel);

        // Display Hotel Details in Table
        for(int i = 0; i < this.controller.getHotelObjects().size(); i++) {
            tableModel.addRow(new Object[] {this.controller.getHotelObjects().get(i).getName(),
                                            this.controller.getHotelObjects().get(i).getBaseRate(),
                                            this.controller.getHotelObjects().get(i).getRoomList().size(),
                                            this.controller.getHotelObjects().get(i).getReservationManager().getReservationList().size()});
        }
        
        // SELECTION MODEL
        hotelListTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        // hotelListTable.setCellSelectionEnabled(true);

        ListSelectionModel selectionModel = hotelListTable.getSelectionModel();

        selectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                handleSelection(event);
            }
        });

        hotelListScrollPane.setViewportView(hotelListTable);

        add(hotelListScrollPane);
        hotelListScrollPane.setBounds(20, 20, 530, 370);


        viewReservationButton.setText("View Hotel Reservation List");
        add(viewReservationButton);
        viewReservationButton.addActionListener(this);
        viewReservationButton.setBounds(20, 420, 190, 23);
        
        refreshButton.setText("Refresh Table");
        add(refreshButton);
        refreshButton.addActionListener(this);
        refreshButton.setBounds(440, 420, 110, 23);

        viewRoomButton.setText("View Hotel Room List");
        add(viewRoomButton);
        viewRoomButton.addActionListener(this);
        viewRoomButton.setBounds(230, 420, 190, 23);
    }

    private void handleSelection(ListSelectionEvent event) {
        if(event.getValueIsAdjusting()) {
            return;
        }

        String strSource = event.getSource().toString();
        System.out.println(hotelListTable.getColumnName(hotelListTable.getSelectedColumn()));
        System.out.println(hotelListTable.getSelectedRow());
        System.out.println(hotelListTable.getSelectedColumn());
        System.out.println(strSource);
    }

    public void actionPerformed(ActionEvent event) {
        if(event.getSource() == viewReservationButton) {
            System.out.println("View Reservation");
            new SubFrame(new ReservationListPanel(controller, hotelListTable.getSelectedRow()));
            // TODO: implement view more button
        }
        else if(event.getSource() == refreshButton) {
            refreshPanel();
        }
        else if(event.getSource() == viewRoomButton) {
            System.out.println("View Room");
            new SubFrame(new RoomListPanel(controller, hotelListTable.getSelectedRow()));
            // TODO: add functionality here
        }
    }

    /**
     * Refreshes this panel.
     */
    private void refreshPanel() {
        System.out.println("Refreshing Panel...");
        this.removeAll();
        this.initComponents();
        this.repaint();
        this.revalidate();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane hotelListScrollPane;
    private javax.swing.JTable hotelListTable;
    // End of variables declaration//GEN-END:variables
}
