package view;

import controller.HotelReservationSystemController;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Rafael
 */
public class CreateHotel extends javax.swing.JPanel {
    HotelReservationSystemController controller;

    /**
     * Creates new form CreateHotel
     */
    public CreateHotel(HotelReservationSystemController controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hotelListScrollPane = new javax.swing.JScrollPane();
        hotelListTable = new javax.swing.JTable();
        roomNameTextField = new javax.swing.JTextField();
        hotelNameTextField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        roomNameLabel = new javax.swing.JLabel();
        hotelNameLabel = new javax.swing.JLabel();
        roomTypeDropDown = new javax.swing.JComboBox<>();
        roomTypeLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(570, 480));
        setLayout(null);

        // SET UP TABLE
        String hotelListHeader[] = {"Hotel Name"};
        DefaultTableModel hotelListModel = new DefaultTableModel(0, 0);

        hotelListModel.setColumnIdentifiers(hotelListHeader);
        hotelListTable.setModel(hotelListModel);
        
        // ADD OBJECT TO TABLE
        for(int i = 0; i < controller.getHotelObjects().size(); i++) {
            hotelListModel.addRow(new Object[] {controller.getHotelObjects().get(i).getName()});
        }


        hotelListScrollPane.setViewportView(hotelListTable);
        if (hotelListTable.getColumnModel().getColumnCount() > 0) {
            hotelListTable.getColumnModel().getColumn(0).setResizable(false);
        }

        add(hotelListScrollPane);
        hotelListScrollPane.setBounds(20, 20, 520, 250);

        roomNameTextField.setText("Enter Room Name");
        roomNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNameTextFieldActionPerformed(evt);
            }
        });
        add(roomNameTextField);
        roomNameTextField.setBounds(110, 350, 430, 22);

        hotelNameTextField.setText("Enter Hotel Name");
        hotelNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelNameTextFieldActionPerformed(evt);
            }
        });
        add(hotelNameTextField);
        hotelNameTextField.setBounds(110, 300, 430, 22);

        cancelButton.setText("Cancel");
        add(cancelButton);
        cancelButton.setBounds(440, 410, 100, 23);

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        add(confirmButton);
        confirmButton.setBounds(330, 410, 100, 23);

        roomNameLabel.setText("Room Name:");
        add(roomNameLabel);
        roomNameLabel.setBounds(30, 350, 80, 20);

        hotelNameLabel.setText("Hotel Name:");
        add(hotelNameLabel);
        hotelNameLabel.setBounds(30, 300, 80, 20);

        // roomTypeDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        // roomTypeDropDown.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         roomTypeDropDownActionPerformed(evt);
        //     }
        // });

        String roomTypes[] = {"Standard", "Deluxe", "Executive"};
        DefaultComboBoxModel<String> roomTypeModel = new DefaultComboBoxModel<>(roomTypes);
        roomTypeDropDown.setModel(roomTypeModel);
        roomTypeDropDown.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent event) {
                roomTypeDropDownItemStateChanged(event);
            }
        });
        

        add(roomTypeDropDown);
        roomTypeDropDown.setBounds(110, 410, 200, 22);

        roomTypeLabel.setText("Room Type:");
        add(roomTypeLabel);
        roomTypeLabel.setBounds(30, 410, 70, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void roomNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNameTextFieldActionPerformed
        // TODO add your handling code here:
        System.out.println(roomNameTextField.getText());
    }//GEN-LAST:event_roomNameTextFieldActionPerformed

    private void hotelNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotelNameTextFieldActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        controller.createNewHotel(hotelNameTextField.getText());
        this.removeAll();
        this.initComponents();
        this.repaint();
        this.revalidate();

    }//GEN-LAST:event_confirmButtonActionPerformed

    private void roomTypeDropDownItemStateChanged(ItemEvent event) {//GEN-FIRST:event_roomTypeDropDownActionPerformed
        // TODO add your handling code here:
        if(event.getStateChange() == ItemEvent.SELECTED) {
            switch (roomTypeDropDown.getSelectedIndex()) {
                case 0:
                    System.out.println("Standard");
                    break;
                case 1:
                    System.out.println("Deluxe");
                    break;
                case 2:
                    System.out.println("Executive");
                    break;
                default:
                    System.out.println("DEFAULT");
                    break;
            }
        }
    }//GEN-LAST:event_roomTypeDropDownActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JScrollPane hotelListScrollPane;
    private javax.swing.JTable hotelListTable;
    private javax.swing.JLabel hotelNameLabel;
    private javax.swing.JTextField hotelNameTextField;
    private javax.swing.JLabel roomNameLabel;
    private javax.swing.JTextField roomNameTextField;
    private javax.swing.JComboBox<String> roomTypeDropDown;
    private javax.swing.JLabel roomTypeLabel;
    // End of variables declaration//GEN-END:variables
}
