/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.HotelReservationSystemController;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Rafael
 */
public class HotelListViewPanel extends javax.swing.JPanel {
    HotelReservationSystemController controller;

    /**
     * Creates new form ViewHotelPanel
     */
    public HotelListViewPanel(HotelReservationSystemController controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hotelListScrollPane = new javax.swing.JScrollPane();
        hotelListTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(570, 480));
        setLayout(null);

        hotelListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Hotel Name", "Base Rate", "No. of Rooms", "No. of Reservations"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });

        // SELECTION MODEL
        hotelListTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        hotelListTable.addRowSelectionInterval(0, 3);

        ListSelectionModel selectionModel = hotelListTable.getSelectionModel();

        selectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                handleSelection(event);
            }
        });

        hotelListScrollPane.setViewportView(hotelListTable);

        add(hotelListScrollPane);
        hotelListScrollPane.setBounds(20, 20, 530, 440);
    }// </editor-fold>//GEN-END:initComponents

    private void handleSelection(ListSelectionEvent event) {
        if(event.getValueIsAdjusting()) {
            return;
        }

        String strSource = event.getSource().toString();
        System.out.println(strSource);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane hotelListScrollPane;
    private javax.swing.JTable hotelListTable;
    // End of variables declaration//GEN-END:variables
}
